
---
- hosts: node
  tasks:
  - name:  Create multiple files at a time
    file:
      dest: "{{ item }}"
      mode: 0755
      state: touch
    with_items:
    - /home/ubuntu/practise/file1.txt
    - /home/ubuntu/practise/file2.txt
    - /home/ubuntu/practise/file3.txt
